name: ci-with-ssh

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show remote dirs
        uses: garygrossgarten/github-action-ssh@release
        with: 
          command: ls -al
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          privateKey: ${{ secrets.REMOTE_KEY }}
