name: ci-with-ssh

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show remote dirs
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with: 
          command: /application/hello.sh
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          privateKey: ${{ secrets.REMOTE_KEY }}
